### ISSUE TITLE
Implement Send + Sync for Chain

### ISSUE THREAD

**Issue by indiv0** [aatxe/markov#13]
As it is, I can't use `Chain` in a threaded context because it uses `Rc` internally (hence, `Sync` is not implemented). I'd very much like to be able to use it in a threaded context, so I was hoping you could find a way to make this lib thread-safe (through `Arc` or something).

**Comment by thiolliere** [comment]
I think the solution would be to ask the user to provide a token that implements clone.

**Comment by thiolliere** [comment]
related: #17

**Comment by aatxe** [comment]
#18 was merged and addresses this.
