### ISSUE TITLE
generate_str_from_token when order > 1

### ISSUE THREAD

**Issue by Follpvosten** [aatxe/markov#19]
When I have a Chain<String> with an `order` of 2 or higher, a token should be a Vec<String> if I'm getting this right.

Since `generate_str_from_token` only accepts a `&str` and never converts that to a Vec, it's impossible for `generate_str_from_token` to succeed in this scenario, as far as I can tell.

Have I gotten something wrong? If so, how do I use this method on a Chain<String> of order 2+? If not, is this intended behaviour or a bug?

Thanks for the great work on this library!

**Comment by aatxe** [comment]
The current behavior of generate_from_token (which is used by generate_str_from_token) is to interpret the token in a higher-order context with repetition, i.e. if your chain is order 2 and your token is "cat", it'll try to start from the vector `[Some("cat"), Some("cat")]`. I'm rather removed from the context in which this decision was made. So, I can't say if it's a bug exactly, but I agree that it seems less useful than the apparent alternative: starting from the token `[None, Some("cat")]` which corresponds more directly to how the chain is created in feed.
