### ISSUE TITLE
Project not public domain in certain juristictions

### ISSUE THREAD

**Issue by skade** [aatxe/markov#3]
The Unlicense is a bad public domain license, as it does not care about different juristdictions at all. Current reading is that using code under Unlicense is a copyright violation in Germany, for example (and all other countries where you get certain unwaivable rights granted by default).

See http://projects.opensource.org/pipermail/license-review/2012-January/000052.html for an explanation.

For that reason, the GNU project recommends using the CC0 instead. https://www.gnu.org/philosophy/license-list.html#Unlicense

IANAL, but I'm also sure that I cannot sign the CLA were I intending to commit to this project.

**Comment by aatxe** [comment]
CC0 isn't really intended for code though. That presents its own issue. I'm not sure what the best course of action would be.

**Comment by skade** [comment]
It actually is. CC0 is - in contrast to all other CC-licenses - declared as fit for source code, as it is just a waiver of rights to the fullest extend possible.

https://wiki.creativecommons.org/CC0_FAQ => "May I apply CC0 to computer software? If so, is there a recommended implementation?"

**Comment by aatxe** [comment]
It's always been indicated to me that this was not the case. I'm going to have to go migrate everything to CC0 later. Thanks for letting me know!

**Comment by skade** [comment]
\o/ Thank you! Fell into the same trap for a some time, happy to help.

**Comment by aatxe** [comment]
Okay, this project (and all the other public domain projects I'm actively maintaining) are now CC0. Cheers! :)
