### ISSUE TITLE
Replace JSON serialization with custom serialization.

### ISSUE THREAD

**Issue by aatxe** [aatxe/markov#5]
We need to do some custom serialization here. JSON has forced constraints like specifying a start/end marker and is incompatible with higher-order chains as implemented by @BenBergman. The reason for this is that in JSON, the only valid object key is a string. So, we'll need to implement our own format to serialize it to (or find another existing format that works better).

**Comment by BenBergman** [comment]
Could we use JSON again if the key was a string formed by concatenating all elements in the list with the original separator used when parsing the input data?

**Comment by aatxe** [comment]
Something of that sort might work, yeah. I'll consider any solution that works well. So, you could certainly try it.

**Comment by thiolliere** [comment]
This must be doable by implementing serde serialize and deserialize when T is serialize and deserialize respectively

**Comment by aatxe** [comment]
Fixed in `5655cd4a166a2f6822508cba6d67511ef2069d2e`
