### ISSUE TITLE
Large files in cargo package source

### ISSUE THREAD

**Issue by bluss** [aatxe/markov#8]
markov 0.0.30 has a 11MB log file in its cargo package source. Consider releasing a new clean version.

This is a reminder that cargo includes all non-ignored files in your working directory when you publish — look at `git status` before you publish.

(I downloaded all crates.io crates and I started to grep for junk)

**Comment by aatxe** [comment]
Hah, thanks. I've added them to the gitignore, and I'll publish a new version without it.

**Comment by bluss** [comment]
Thanks!
